
name: Build and Test

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build APK & upload to Github Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: mkdir temp && cp ./build/app/outputs/apk/debug/app-debug.apk temp/
      - name: Prepare app repo
        uses: addnab/docker-run-action@v3
        with:
          image: am271/fdroid:latest
          options: -v ${{ env.PWD }}/temp:/app/repo
          run: echo "hello"
